# Generated by Django 4.1.3 on 2022-11-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('MENS', 'mens'), ('WOMENS', 'womens'), ('FOOD', 'food'), ('FUNITURE', 'funiture'), ('DIGITAL', 'digital')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.TextField(),
        ),
    ]
