# Generated by Django 4.1.3 on 2022-11-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_products_color_products_eta_products_hotdeal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
